# Generated by Django 2.2.7 on 2019-11-05 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('producer', models.TextField()),
                ('expiration_date', models.DateField()),
                ('storage', models.CharField(choices=[('n', 'Normal'), ('c', 'Fridge'), ('f', 'Frezzer'), ('o', 'Other')], max_length=1)),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
    ]
